### ISSUE TITLE
HttpCredentialsAdapter should refresh credentials if access token invalid

### ISSUE THREAD

**Issue by anthmgoogle** [google/google-auth-library-java#14] opened 2015-05-18 18:53 UTC
An access token can become invalid separately from its expiration time due a clock mismatch or other scenarios. If a request fails because the access token is invalid, the adapter should call refresh() to discard the token and retry the request a single time. See google-api-java-client for a reference implementation.

**Comment by garrettjonesgoogle** [comment] 2017-03-10 22:45
@anthmgoogle : bug or enhancement?

**Comment by chingor13** [comment] 2018-06-19 23:29
Duplicate of #22. Closing this one in favor of that one as it has more links.

**Closed by chingor13** 2018-06-19 23:29 UTC
Labels: :rotating_light:, triage me
